[package]
name = "voices-to-text"
version = "0.1.0"
authors = ["Ilya Titkov <ilya@titkov.me>"]

[dependencies]
hyper = "0.12"
serde_json = "1.0"
serde = "1.0"
serde_derive = "1.0"
tokio = "0.1"
hyper-tls = "0.3"
base64 = "0.9.2"
futures = "0.1.23"
config = "0.9"
log = "0.4"
env_logger = "0.5"